<div class="page-title">
    <h1><?php echo $this->__('Your order has been received.') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>
<h2 class="sub-title"><?php echo $this->__('Thank you for your purchase!') ?></h2>
<?php if ($this->getOrderId()): ?>
    <p><?php echo $this->__('Your order # is: %s.', $this->escapeHtml($this->getOrderId())) ?></p>
<?php endif; ?>

<?php if ($this->getOrderId()): ?>
    <div class="buttons-set">
        <button id="cloudpayments-pay" type="button" class="button cloudpayments-widget"
                title="<?php echo Mage::helper('core')->quoteEscape($this->__('Pay')) ?>">
            <span><span><?php echo $this->__('Pay') ?></span></span></button>
    </div>
    <script src="https://widget.cloudpayments.ru/bundles/cloudpayments"></script>
    <script>
        var widget = new cp.CloudPayments({language: '<?= $this->getLang() ?>'});
        widget.<?php echo $this->getStepMethod() ?>(<?php echo json_encode($this->getWidgetParams()) ?>, '<?php echo $this->getSuccessPage() ?>', '<?php echo $this->getErrorPage() ?>');
    </script>
<?php endif ?>